export const classesData =[
  {
    profile:'https://images7.alphacoders.com/122/1221596.png',
    cover:'https://c4.wallpaperflare.com/wallpaper/1020/1/213/world-of-warcraft-battle-for-azeroth-video-games-warcraft-alliance-wallpaper-preview.jpg',
    name:'anime',
    teacherName:'nesuko',
    studentCount:'500'
  },
  {
    profile:'https://images7.alphacoders.com/122/1221596.png',
    cover:'https://c4.wallpaperflare.com/wallpaper/1020/1/213/world-of-warcraft-battle-for-azeroth-video-games-warcraft-alliance-wallpaper-preview.jpg',
    name:'anime',
    teacherName:'nesuko',
    studentCount:'500'
  },
  {
    profile:'https://images7.alphacoders.com/122/1221596.png',
    cover:'https://c4.wallpaperflare.com/wallpaper/1020/1/213/world-of-warcraft-battle-for-azeroth-video-games-warcraft-alliance-wallpaper-preview.jpg',
    name:'anime',
    teacherName:'nesuko',
    studentCount:'500'
  },
  {
    profile:'https://images7.alphacoders.com/122/1221596.png',
    cover:'https://c4.wallpaperflare.com/wallpaper/1020/1/213/world-of-warcraft-battle-for-azeroth-video-games-warcraft-alliance-wallpaper-preview.jpg',
    name:'anime',
    teacherName:'nesuko',
    studentCount:'500'
  }
]